### ISSUE TITLE
New line scroll bottom

### ISSUE THREAD

**Issue by koca** [koca/vue-prism-editor#1]
When we add a new line it should scroll to bottom if the line is the last line on the screen

**Comment by ipsrt** [comment]
I'd find this super helpful. vue-prism-editor fits my needs exactly except for the fact that it seems laggy/unresponsive when <enter> doesn't scroll down

**Comment by ordinov** [comment]
this is something you can easily do with:

```css
div.prism-editor-wrapper {
    max-height: 200px;
    overflow-y: auto;
}
```
