### ISSUE TITLE
Line number misalign with code

### ISSUE THREAD

**Issue by valentinoli** [koca/vue-prism-editor#117]
I have around 150 lines of code, and the line numbers misalign with the code lines. Do you know how I can fix this? I am using version 1.2.2.

![image](https://user-images.githubusercontent.com/23453691/129736475-125ecdbc-fddf-44a3-ab81-7b5feae8018e.png)

**Comment by valentinoli** [comment]
My code:

```html
<template>
  <client-only placeholder="Loading...">
    <!-- line numbers don't align correctly -->
    <prism-editor
      v-model="code"
      v-bind="$attrs"
      :auto-style-line-numbers="false"
      class="my-editor my-6"
      :highlight="highlighter"
      style="max-height: 300px"
    ></prism-editor>
  </client-only>
</template>
```

```css
/* required class */
.my-editor {
  /* we dont use `language-` classes anymore so thats why we need to add background and text color manually */
  background: #2d2d2d;
  color: #ccc;

  /* you must provide font-family font-size line-height. Example: */
  font-family: Fira code, Fira Mono, Consolas, Menlo, Courier, monospace;
  font-size: 14px;
  line-height: 1.5;
  padding: 5px;
}

/* optional class for removing the outline */
.prism-editor__textarea:focus {
  outline: none;
}
```
