### ISSUE TITLE
Line numbers only partially showing

### ISSUE THREAD

**Issue by BenBE** [koca/vue-prism-editor#75]
When packing the VuePrismEditor component into the body of a ExpansionPanel container the line numbers aren't properly showing when the expansion panel is initially collapsed.

Debugging the issue indicated that https://github.com/koca/vue-prism-editor/blob/31b1fddb1406d9d257f00c2c73a784205bc68314/src/components/Editor.vue#L178 is read while the DOM has not been updated yet and thus some delay is needed.

```js
var csHeight = getComputedStyle(this.$refs.pre).height
if (csHeight=="auto") {
  window.setTimeout(() => {
    this.lineNumbersHeight = getComputedStyle(this.$refs.pre).height;
  }, 1);
} else {
      this.lineNumbersHeight = csHeight;
}
```

Seems to resolve the issue. Calling `this.$nextTick()` does not seem to work for me.

**Comment by koca** [comment]
Hey @BenBE thanks for the report! Could you reproduce this issue on codesandox?

**Comment by BenBE** [comment]
I can try if I get a minimal setup to work, but this might take some time.

Basic setup I used is:
```html
      <v-expansion-panels focusable multiple ripple :value="configFileSelected">
        <v-expansion-panel v-for="(configFile, configFileIdx) in configFiles" v-bind:key="configFileIdx" @change="editorHeightUpdate">
          <v-expansion-panel-header>
            <v-card-title v-if="configFile.type=='system'">
              <b>System Configuration:</b>
              <tt>{{configFile.name}}</tt>
            </v-card-title>
            <v-card-title v-else>
              <b>{{configFile.type}}:</b>
              <tt>{{configFile.name}}</tt>
            </v-card-title>
          </v-expansion-panel-header>
          <v-expansion-panel-content>
            <prism-editor
              v-model="configFile.content"
              :ref="configFileIdx"
              language="xml"
              line-numbers
              emit-events
              auto-style-line-numbers
              class="match-braces" style="max-height:50vh;">
            ></prism-editor>
          </v-expansion-panel-content>
        </v-expansion-panel>
      </v-expansion-panels>
```

With some minor CSS:
```css
.v-expansion-panel-header .v-card__title {
    padding: 0;
}
.v-expansion-panel-header .v-card__title b {
    display: inline-block;
    min-width: 12em;
}

.v-expansion-panel-content__wrap {
    padding: 0;
}

.prism-editor-wrapper .prism-editor__line-number {
    margin:0em;
    margin-left:1em;
    min-width:3em;
    padding-right:1em;
}
.prism-editor-wrapper .prism-editor__line-number:nth-of-type(odd) {
    background-color:rgb(0,0,0,0.04);
}

.prism-editor-wrapper pre {
    min-width:min-content;
}
.prism-editor-wrapper pre>code {
    min-width:100%;

	background-color: #fdfdfd;
	background-image: linear-gradient(transparent 50%, rgba(0, 0, 0, 0.02) 50%);
	background-size: 3em 3em;
	background-origin: content-box;
	background-attachment: local;
}
.prism-editor-wrapper .prism-editor__code {
    padding-left:0px;
}
```

And some supporting JS:
```js
export default {
    data: () => ({
        configFileSelected: [1],
        configFiles: []
    }),
    sockets: {
        conf_get: function(msg) {
          this.showConfig(msg)
        },
    },
    watch: {
        configFileSelected: {
          deep: true,
          immediate: true,
          handler: function() {
            this.editorHeightUpdate()
          }
        }
    },
    mounted: function () {
        this.$socket.emit('conf_get', this.showConfig);
    },
    destroyed: function () {
    },
    methods: {
        showConfig: function(msg) {
          this.configFiles = []
          if(msg) {
            msg.forEach(f => {
              this.configFiles.push(f)
            })
          }
        },

        editorHeightUpdate: function() {
          window.setTimeout(() => {
            for (var ref in this.$refs) {
              var refObj = this.$refs[ref][0]
              if(refObj.setLineNumbersHeight) {
                refObj.setLineNumbersHeight()
              }
            }
          }, 1);
        }
    }
}
```

That's the fixed version, the one calling `this.$nextTick()` to have the editors updated did not work, but only showed the first few line numbers of the editor (but not those not directly visible without scrolling that panel).

HTH.
